services:
  db_artist:
    image: postgres:16.3
    container_name: db_artist
    env_file:
      - ./conf/db/.env
    ports:
      - "5434:5432"
    volumes:
      - db_artist:/var/lib/postgresql/data
    networks:
      - backend_artist
    restart: on-failure

volumes:
  db_artist:

networks:
  backend_artist: