server:
  port: 8085

spring:
  application:
    name: artist-api
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5434/artist_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  mvc:
    servlet:
      path: /api

discogs:
  api:
    url: https://api.discogs.com
  consumer:
    key: atReCrcFEWtpwVLSOqFc
    secret: BtMnrHOxToVbtvmAbJJChVnssjSvbPRZ
